import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Container } from "react-bootstrap";
import Link from "next/link";
import { stats } from "@/constants/stats";
import { coreValues } from "@/constants/values";
import NextImage from "@/hooks/NextImage";
import { services } from "@/constants/services";
import { projects } from "@/constants/projects";
import { clients } from "@/constants/clientsAndPartners";
import { FaCalendarAlt } from "react-icons/fa";
import Waves from "@/components/waves";
import { contactInfo } from "@/constants/contactinfor";
import React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>ALIF MARINE & ENGINEERING SERVICES LTD. | AMESL</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <section className={styles.banner}>
          <div className={styles.wrap}>
            <Container>
              <div className={styles.content}>
                <h1>
                  We Provide the Best <span>Technical Solution</span>
                </h1>
                <p>
                  ISO 9001:2008 certified engineering and marine services
                  company providing top-tier solutions since 2007
                </p>
                <div className={styles.btns}>
                  <Link className={styles.one} href="/e">
                    Our Services
                  </Link>
                  <Link className={styles.two} href="/e">
                    Contact Us
                  </Link>
                </div>
              </div>
            </Container>
          </div>
        </section>
        <section className={styles.stats}>
          <div className={styles.bg}>
            <Waves />
          </div>
          <Container className={styles.container}>
            <div className={styles.row}>
              {stats.map((item) => (
                <div key={item.title} className={styles.col}>
                  <div className={styles.icon}>{item.icon}</div>
                  <h2>{item.title}</h2>
                  <p>{item.description}</p>
                </div>
              ))}
            </div>
          </Container>
        </section>

        <section className={styles.values}>
          <Container>
            <div className={styles.head}>
              <h2>Our Core Values</h2>
              <p>
                The principles that guide our operations and define our
                commitment to excellence in marine engineering services.
              </p>
            </div>
            <div className={styles.row}>
              {coreValues.map((item) => (
                <div key={item.title} className={styles.col}>
                  <div className={styles.icon}>{item.icon}</div>
                  <h3>{item.title}</h3>
                  <p>{item.description}</p>
                </div>
              ))}
            </div>
          </Container>
        </section>

        <section id="about" className={styles.about}>
          <Container>
            <div className={styles.head}>
              <h2>About Us</h2>
              <p>
                Alif Marine & Engineering Services Ltd (AMESL) being a service
                and supply company in the middle of 2007 to cater the needs of
                Marine, Industries, Oil, Gas and Power sectors in Bangladesh.
              </p>
              <p>
                AMESL has come a long way since then. It had started with
                virtually no tangible assets to use and only marginal capital
                but has now acquired a fleet of specialized equipment for
                providing logistical support to a wide range of projects in
                Bangladesh.
              </p>
            </div>
            <div className={styles.row}>
              <div className={styles.content}>
                <p>
                  Since inception, AMESL has been involved in some capacity of
                  other in all world-class projects in Bangladesh. It has built
                  up a reputation for completing jobs ahead of schedules. It
                  lives up to the philosophy of completing a job as fast as
                  safety allows by giving pleasant surprise to our clients and
                  then moving into the next job.
                </p>
                <p>
                  At present, AMESL carries specialized and general Operators
                  and Technicians of high performance levels on its payroll. In
                  addition, it has standing arrangement with world-class
                  Professionals and other companies at home and abroad in
                  different fields of specialization to work as associates, as
                  and when needed. This adds both extra strength and
                  professional capacity in our taking up even new challenging
                  jobs with confidence.
                </p>
                <p>
                  It has a very strong co-partnership with Singmar Marine Pte
                  Ltd., Thome-Ship Management Pte Ltd. and other well-reputed
                  Marine & Offshore company at Singapore.
                </p>
                <p>
                  It meets various requirements of local and foreign companies
                  and contractors working in Bangladesh. The target is to set up
                  a mini Offshore Supply Base in association with foreign
                  partners at Chittagong, for providing Shore and Marine
                  accessed support services. The Offshore supply base will stock
                  Materials, Consumable, Equipment and Spares on both sale and
                  rental basis.
                </p>
              </div>
              <div className={styles.image}>
                <NextImage src={"/images/hm-about.jpg"} alt={""} />
              </div>
            </div>
            <div className={styles.rowTwo}>
              <div className={styles.col}>
                <h3>Our Vision</h3>
                <p>
                  Our vision is to be the best technical service provider in
                  Bangladesh and committed to quality.
                </p>
              </div>
              <div className={styles.col}>
                <h3>Our Mission</h3>
                <p>
                  To deliver high-quality, cost-effective engineering solutions
                  that exceed client expectations while maintaining the highest
                  standards of safety and environmental responsibility.
                </p>
              </div>
              <div className={styles.col}>
                <h3>Main Policy</h3>
                <p>
                  The main policy of ALIF MARINE & ENGINEERING SERVICES LTD is
                  to attain customers’ satisfaction and confidence as top
                  priority. We strive to reach the highest possible standard of
                  quality services, so that our customer acquire total
                  satisfaction for the money they spend for the services and
                  products.
                </p>
              </div>
            </div>
            <div className={styles.message}>
              <div className={styles.image}>
                <NextImage src={"/images/user.png"} alt={""} />
              </div>
              <div className={styles.content}>
                <h3>Message from the Managing Director</h3>
                <p>
                  In the light of highly competitive and fast growing market,
                  shipping and industrial sectors need proper combination of
                  commitment and quality services to succeed in the competition
                  of business. To ensure the fulfillment of the above mentioned
                  combination, both sectors need to be supported by quality
                  service providers and knowledgeable and dedicated professional
                  around. But lack of quality service providers and most
                  importantly, lack of commitment to timely complete the
                  required services in safe and effective fashion cause both the
                  sector a huge setback.
                </p>
                <p>
                  Considering the above scenario, we are pleased to introduce
                  ourselves as one of the established Engineering firm which is
                  based in Chittagong and organized by a group of highly
                  experienced, qualified, energetic and motivated marine
                  professionals with a motto to provide quality services and to
                  take care of all those things with our competence, organizing
                  skill and dedication. Our main focus is sustainable
                  development in both Shipping & Industrial sector with creative
                  and innovative ideas. We are committed to take care of you
                  whenever needed. We are fully equipped, well organized and
                  skilled in our respective sectors. The team comprises of
                  following marine engineers and professionals.
                </p>
              </div>
            </div>
          </Container>
        </section>

        <section className={styles.services}>
          <Container>
            <div className={styles.head}>
              <h2>Our Services</h2>
            </div>
            <div className={styles.row}>
              {services.slice(0, 6).map((item) => (
                <div key={item.title} className={styles.col}>
                  <div className={styles.image}>
                    <NextImage src={"/images/hm-about.jpg"} alt={item.title} />
                  </div>
                  <div className={styles.content}>
                    <h3>{item.title}</h3>
                    <p>{item.description}</p>
                  </div>
                </div>
              ))}
            </div>
            <div className={styles.btn}>
              <Link className={styles.one} href="/e">
                View All Services
              </Link>
            </div>
          </Container>
        </section>

        <section className={styles.projects}>
          <Container>
            <div className={styles.head}>
              <h2>Our Projects</h2>
            </div>
            <div className={styles.row}>
              {projects.slice(0, 6).map((item) => (
                <div key={item.title} className={styles.col}>
                  <div className={styles.image}>
                    <NextImage src={"/images/hm-banner.jpg"} alt={item.title} />
                  </div>
                  <div className={styles.content}>
                    <h3>{item.title}</h3>
                    <p>{item.description}</p>
                    <h4 className={styles.date}>
                      <FaCalendarAlt /> {item.date}
                    </h4>
                  </div>
                </div>
              ))}
            </div>
            <div className={styles.btn}>
              <Link className={styles.one} href="/e">
                View All Projects
              </Link>
            </div>
          </Container>
        </section>
        <section id="clients" className={styles.clients}>
          <Container>
            <div className={styles.head}>
              <h2>Our Clients & Partners</h2>
              <p>
                We're proud to serve and collaborate with leading organizations
                in the marine and industrial sectors.
              </p>
            </div>
            <div className={styles.row}>
              {clients.map((item) => (
                <div key={item.id} className={styles.col}>
                  <div className={styles.image}>
                    <NextImage src={item.logo} alt={item.name} />
                  </div>
                </div>
              ))}
            </div>
          </Container>
        </section>

        <section id="contacts" className={styles.contact}>
          <Container>
            <div className={styles.head}>
              <h2>Contact Us</h2>
              <p>
                Get in touch with our team for inquiries, quotes, or to discuss
                your project requirements.
              </p>
            </div>
            <div className={styles.row}>
              <div className={styles.form}>
                <form>
                  <div className={styles.field}>
                    <label htmlFor="">Full Name</label>
                    <input type="text" />
                  </div>
                  <div className={styles.field}>
                    <label htmlFor="">Email Address</label>
                    <input type="text" />
                  </div>

                  <div className={styles.field}>
                    <label htmlFor="">Phone Number</label>
                    <input type="text" />
                  </div>
                  <div className={styles.field}>
                    <label htmlFor="">Message</label>
                    <textarea name="" id=""></textarea>
                  </div>
                  <div className={styles.btn}>
                    <button>Send Message</button>
                  </div>
                </form>
              </div>
              <div className={styles.contactInfo}>
                <div className={styles.us}>
                  <h3>Contact Information</h3>
                  <ul>
                    {contactInfo.map((field, index) => (
                      <li key={index}>
                        <span className={styles.icon}>{field.icon}</span>
                        <span className={styles.text}>
                          {field.value.map((val, i) => {
                            let href = "";

                            if (field.linkType === "email") {
                              href = `mailto:${val}`;
                            } else if (field.linkType === "phone") {
                              href = `tel:${val.replace(/\s+/g, "")}`;
                            }

                            return (
                              <React.Fragment key={i}>
                                {href ? <a href={href}>{val}</a> : val}
                                {i < field.value.length - 1 && <br />}
                              </React.Fragment>
                            );
                          })}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
                <div className={styles.map}>
                  <iframe
                    src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d3690.4961390219705!2d91.78474827599435!3d22.33488779163964!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1s24%2C%20Halishahar%20H%2FE%2C%20R%2301%2C%20Block-H%2C%20Halishahar%2C%20Chattogram-4216%2C%20Bangladesh!5e0!3m2!1sen!2sin!4v1754990032028!5m2!1sen!2sin"
                    loading="lazy"
                    referrerPolicy="no-referrer-when-downgrade"
                  ></iframe>
                </div>
              </div>
            </div>
          </Container>
        </section>
      </main>
    </>
  );
}
