import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Container } from "react-bootstrap";
import Link from "next/link";
import { whyChoose } from "@/constants/whyChoose";
import { getStarted } from "@/constants/getStarted";
import NextImage from "@/hooks/NextImage";
import {
  FaChartLine,
  FaDownload,
  FaLock,
  FaMobileAlt,
  FaRocket,
} from "react-icons/fa";
import React from "react";
import { BsBoxArrowInRight } from "react-icons/bs";
import {
  FaArrowRightLong,
  FaHandsHolding,
  FaRegCircleQuestion,
} from "react-icons/fa6";
import { paymentPartner } from "@/constants/paymentPartner";
import { growBusiness } from "@/constants/growBusiness";
import { security } from "@/constants/security";
import Testimonials from "@/components/testimonials/testimonials";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          BD PAY | Bangladesh's next-generation digital payment gateway — fast,
          secure, and built for everyone
        </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <section className={styles.banner}>
          <div className={styles.wrap}>
            <Container>
              <div className={styles.content}>
                <h1>Simplify Your Payments with BD PAY</h1>
                <p>
                  Bangladesh's next-generation digital payment gateway — fast,
                  secure, and built for everyone. Send money, pay bills, shop
                  online, and grow your business — all in one app.
                </p>
                <div className={styles.btns}>
                  <Link className={styles.one} href="/e">
                    <BsBoxArrowInRight /> Get Started
                  </Link>
                  <Link className={styles.two} href="/e">
                    <FaDownload /> Download App
                  </Link>
                </div>
              </div>
            </Container>
          </div>
        </section>
        <section className={styles.whyChoose}>
          <Container className={styles.container}>
            <div className={styles.head}>
              <h2>
                <FaRegCircleQuestion /> Why Choose BD PAY?
              </h2>
              <p>
                Experience the most comprehensive digital payment solution in
                Bangladesh
              </p>
            </div>
            <div className={styles.row}>
              {whyChoose.map((item) => (
                <div key={item.title} className={styles.col}>
                  <div className={styles.icon}>{item.icon}</div>
                  <h2>{item.title}</h2>
                  <p>{item.description}</p>
                </div>
              ))}
            </div>
          </Container>
        </section>

        <section className={styles.getStarted}>
          <Container>
            <div className={styles.head}>
              <h2>
                <FaRocket /> Getting Started is Easy
              </h2>
              <p>
                Join thousands of users who have already simplified their
                payment experience
              </p>
            </div>
            <div className={styles.row}>
              {getStarted.map((item) => (
                <div key={item.title} className={styles.col}>
                  <div className={styles.icon}>{item.number}</div>
                  <h3>{item.title}</h3>
                  <p>{item.description}</p>
                  <div className={styles.icons}>
                    {item.icon}
                    {item.icon2}
                  </div>
                </div>
              ))}
            </div>
          </Container>
        </section>

        <section className={styles.paymentPartner}>
          <Container>
            <div className={styles.row}>
              <div className={styles.content}>
                <h2>
                  <FaHandsHolding />
                  Your Everyday Payment Partner
                </h2>
                <p>
                  Experience the convenience of managing all your financial
                  needs with a single app. BD PAY makes daily transactions
                  simple, fast, and secure.
                </p>
                <ul>
                  {paymentPartner.map((item) => (
                    <li key={item.title}>
                      <div className={styles.icon}>{item.icon}</div>
                      <div className={styles.text}>
                        <h3>{item.title}</h3>
                        <p>{item.description}</p>
                      </div>
                    </li>
                  ))}
                </ul>

                <div className={styles.btn}>
                  <Link className={styles.one} href="/services">
                    Download App <FaDownload />
                  </Link>
                </div>
              </div>
              <div className={styles.image}>
                <NextImage src={"/images/app.svg"} alt={""} />
              </div>
            </div>
          </Container>
        </section>

        <section className={styles.growBusiness}>
          <Container>
            <div className={styles.row}>
              <div className={styles.image}>
                <NextImage src={"/images/grow.jpg"} alt={""} />
              </div>
              <div className={styles.content}>
                <h2>
                  <FaChartLine />
                  Grow Your Business with BD PAY
                </h2>
                <p>
                  Streamline your payment collection, increase sales, and manage
                  your business finances efficiently with BD PAY's merchant
                  solutions.
                </p>
                <ul>
                  {growBusiness.map((item) => (
                    <li key={item.title}>
                      <div className={styles.icon}>{item.icon}</div>
                      <div className={styles.text}>
                        <h3>{item.title}</h3>
                        <p>{item.description}</p>
                      </div>
                    </li>
                  ))}
                </ul>

                <div className={styles.btn}>
                  <Link className={styles.one} href="/services">
                    Become a Merchant <FaArrowRightLong />
                  </Link>
                </div>
              </div>
            </div>
          </Container>
        </section>

        <section className={styles.security}>
          <Container className={styles.container}>
            <div className={styles.head}>
              <h2>
                <FaLock /> Safe, Reliable & Trusted
              </h2>
              <p>
                BD PAY uses advanced encryption, biometric security, and fraud
                detection systems to ensure your transactions are always
                protected.
              </p>
            </div>
            <div className={styles.row}>
              {security.map((item) => (
                <div key={item.title} className={styles.col}>
                  <div className={styles.icon}>{item.icon}</div>
                  <h2>{item.title}</h2>
                  <p>{item.description}</p>
                </div>
              ))}
            </div>
          </Container>
        </section>
        <Testimonials />
        <section className={styles.getApp}>
          <Container>
            <div className={styles.row}>
              <div className={styles.content}>
                <div className={styles.icon}>
                  <FaMobileAlt />
                </div>
                <h2>Start Your Digital Payment Journey Today</h2>
                <p>
                  Download BD PAY now and experience the future of payments in
                  Bangladesh.
                </p>

                <div className={styles.btn}>
                  <Link className={styles.one} href="/services">
                    <NextImage src={"/images/google-play.png"} alt={""} />
                  </Link>
                  <Link className={styles.one} href="/services">
                    <NextImage src={"/images/app-store.png"} alt={""} />
                  </Link>
                </div>
              </div>
              <div className={styles.image}>
                <NextImage src={"/images/getapp.png"} alt={""} />
              </div>
            </div>
          </Container>
        </section>
      </main>
    </>
  );
}
